#!/usr/bin/env python3

import io
from lxml import etree
import rnc2rng


''' lxml validation of FPDS ATOM feed using Relax NG XML syntax as input ''' 

with open("../RelaxNG/rfc4287-FPDS.rng", "rb") as f1:
    rng = f1.read()
    schema = etree.parse(io.BytesIO(rng))

with open("../sample-data/sample-feed.xml", "rb") as f2:
    xml = f2.read()
    xmltree = etree.parse(io.BytesIO(xml))

print(xmltree.relaxng(schema))


''' lxml validation of FPDS ATOM feed using Relax NG compact syntax as input '''

# Needs work
